project:
  type: website
  output-dir: docs

website:
  title: "Lance Warwick"
  site-url: https://NotDrLance.github.io
  favicon: images/favicon.png
  navbar:
    logo: images/favicon.png
    left:
      - text: "About"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Teaching"
        href: Teaching.qmd
      - text: "Research"
        href: Research.qmd
      - text: "Blog"
        href: Blog/index.qmd
    tools:
      - icon: cloud
        href: https://bsky.app/profile/sportecostudent.bsky.social

format:
  html:
    theme:
      - minty
      - custom.scss
    css: styles.css
    toc: true



